# Generated by Django 2.0.5 on 2018-05-28 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeCall', models.CharField(choices=[('S', 'Start'), ('E', 'End')], default='S', max_length=10)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 28, 19, 6, 48, 392275))),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
