# Generated by Django 2.0.5 on 2018-05-28 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='call',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 28, 19, 20, 29, 248479)),
        ),
    ]
