# Generated by Django 2.0.5 on 2018-05-28 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0002_auto_20180528_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='destination',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 28, 19, 54, 31, 578194)),
        ),
    ]
