# Generated by Django 2.0.5 on 2018-05-28 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0004_auto_20180528_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassRecord',
            new_name='CallRecord',
        ),
        migrations.AlterField(
            model_name='call',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 28, 20, 51, 5, 341620)),
        ),
    ]
