# Generated by Django 2.0.5 on 2018-05-28 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0005_auto_20180528_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 28, 20, 56, 10, 804139)),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='duration',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
