# Generated by Django 2.0.5 on 2018-05-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0007_auto_20180528_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
    ]
