# Generated by Django 2.0.5 on 2018-05-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0008_delete_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
